### ISSUE TITLE
Got this warning: `bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)`

### ISSUE THREAD

**Issue by jdbzbug** [precious-void/raydium-swap#3] opened 2024-04-01 07:15 UTC
C:\raydium-swap-main>yarn start
yarn run v1.22.22
$ ts-node ./src/index.ts
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
server done

**Comment by precious-void** [comment] 2024-04-04 22:10
Hey, I actually never experienced this kind of issue, but it looks like it's a known bug. Try the solutions from here:
https://solana.stackexchange.com/questions/4077/bigint-failed-to-load-bindings-pure-js-will-be-used-try-npm-run-rebuild-whe

Would love if you can share if one of those solutions had fixed the problem.
🌟

**Comment by precious-void** [comment] 2024-05-02 22:34
Closing this issue for now, feel free to reopen if it reproduces and you have more details.

**Closed as completed by precious-void** 2024-05-02 22:34 UTC
