### ISSUE TITLE
After I do run the program, the program returns the txid normally but when I go to check it, it's an empty transaction

### ISSUE THREAD

**Issue by kevin1027sloth** [precious-void/raydium-swap#7] opened 2024-04-06 07:15 UTC
After I do run the program, the program returns the txid normally but when I go to check it, it's an empty transaction

**Comment by precious-void** [comment] 2024-04-06 14:01
@xiaozhu001 that is an expected behavior. Transaction id is a hash, it doesn't confirm the transaction has actually landed. Currently, in my implementation there is no confirmation check implemented. You can use `connection.confirmTransaction` method to wait for transaction result.

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-08 11:33
I'm using a modified version of your code (thank you by the way) and I am running into the same issues with the blank txn hashes. 

You can confirmTransaction like you said but it is just going to hang until it times out which is terrible for trading. 

I'm using a QuickNode RPC, I can imagine it is worse if you are using a public RPC. 

You could try and use: 

const web3 = require('@solana/web3.js');
web3.sendAndConfirmTransaction()

If your txn isn't getting picked up it could be the priority fee is set way too low as well.

**Comment by precious-void** [comment] 2024-04-08 12:47
@xiaozhu001 @Allen-Taylor welcome to solana 😅

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-09 06:51
> @xiaozhu001 @Allen-Taylor welcome to solana 😅

Yeah right? 

What is the RPC method to see if the cluster even is processing the transaction. Not even confirm/finalized, just that hasn't been dropped. 

https://github.com/StrataFoundation/strata/blob/ab288abb1892161bfae21b955fbc160311ac4eee/packages/spl-utils/src/transaction.ts#L287

These guys have a sendAndConfirmWithRetry function that could be interesting. However they are using raw txns. 

I still haven't found a good solution.

**Comment by precious-void** [comment] 2024-04-10 15:48
@Allen-Taylor you can do the same, get the raw transaction by calling `transaction.serialize()`

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-11 05:22
> @Allen-Taylor you can do the same, get the raw transaction by calling `transaction.serialize()`

I think you have to sign before serializing.

I'm finding checking balance is actually faster than confirming. Your balance will update 2 or 3 seconds before the actual confirmation goes through. 

Handling the dropped transaction is a pain though.  25 seconds is a good estimated timeout.

**Comment by kaiyes** [comment] 2024-04-17 10:03
So you are saying instead of using `raydiumSwap.sendVersionedTransaction `we should use either 
`web3.sendAndConfirmTransaction()`
or
`connection.confirmTransaction ` ? 

Thanks for the repo by the way. Got me furthest. 

<img width="817" alt="Screenshot 2024-04-17 at 4 01 09 PM" src="https://github.com/precious-void/raydium-swap/assets/5293742/082505e4-8590-4654-9e41-580834e85624">

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-17 10:52
I think it is recommended to use get signature statuses for the versioned transactions. 

https://solana.com/docs/rpc/http/getsignaturestatuses

Unfortunately, just because there is a signature doesn't mean it was picked up by the cluster. 

If speed is a concern, I recommend checking the token balance of the wallet along with the signature status. From my experience, the wallet updates 1 or 2 seconds before the status shows success. If the token balance changes you can assume that the buy or sell went through successfully.

**Comment by kaiyes** [comment] 2024-04-17 12:44
Thanks @Allen-Taylor.  that's what I'm doing right now. 

But checking sol balance isn't that bulletproof. I'm almost always seeing the balance unchanged even after waiting a minute. Hence looking for a way to check for transaction confirmation

<img width="897" alt="Screenshot 2024-04-17 at 6 43 12 PM" src="https://github.com/precious-void/raydium-swap/assets/5293742/5ac09a9e-b46f-4758-a415-4c0da1ceedad">

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-17 13:12
You should use the **get signature statuses** method then. 

Do you need an example of the function?

**Comment by kaiyes** [comment] 2024-04-17 13:20
@Allen-Taylor that will be very kind of you. Thank you

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-17 18:20
sorry I misspoke. it is supposed to be getTransaction. 

```

export async function confirmTxn(transactionId: string): Promise<boolean | null> {
const RPC = "your RPC"
try {
  const response = await axios.post<any>(RPC, {
    jsonrpc: '2.0',
    id: 1,
    method: 'getTransaction',
    params: [transactionId, { maxSupportedTransactionVersion: 0 }],
  }, {
    headers: {
      'Content-Type': 'application/json',
    },
  });

  if (!response.data) {
    return null; 
  }

  if (!response.data.result || !response.data.result.meta) {
    throw new Error('Invalid response structure');
  }

  const { err, status } = response.data.result.meta;

  if (status.Ok === null) {
    return true;
  } else {
    return false;
  }
} catch (error) {
  return null; 
}
}

```

**Comment by kaiyes** [comment] 2024-04-18 07:02
Thanks @Allen-Taylor . I moved to jupiter for swapping. Has an api you can call. Works great. 

https://github.com/jup-ag/jupiter-quote-api-node/blob/main/example/index.ts

**Comment by AL-THE-BOT-FATHER** [comment] 2024-04-18 15:22
> Thanks @Allen-Taylor . I moved to jupiter for swapping. Has an api you can call. Works great.
> 
> https://github.com/jup-ag/jupiter-quote-api-node/blob/main/example/index.ts

Yeah Jupiter works great, but if you are trading low liquidity pairs it doesn't work. Jupiter doesn't work for new pairs.

**Comment by umaid56** [comment] 2024-05-20 10:36
Hi @Allen-Taylor 

I stuck for a while with the same issue, the program returns the txid normally but when I go to check it, it's an empty.

What should I do for this? can sendAndConfirmTransaction will be enough for this.

**Comment by AL-THE-BOT-FATHER** [comment] 2024-05-21 07:10
> Hi @Allen-Taylor
> 
> I stuck for a while with the same issue, the program returns the txid normally but when I go to check it, it's an empty.
> 
> What should I do for this? can sendAndConfirmTransaction will be enough for this.

The issue is mostly related to which RPC you are using. Any of the public RPCs are going to be unreliable. Since I have moved to a better quality RPC, I don't have this issue.

Unfortunately, the best way is to set the retries to 0 and spam the txn hash until the block hash expired. A txn hash can be picked up only once, so you don't have to worry about duplicate transactions.

**Comment by umaid56** [comment] 2024-05-21 07:42
First of all thanks for your reply
Currently, I set the retries to 20 and use quick node RPC.

**Comment by AL-THE-BOT-FATHER** [comment] 2024-05-21 12:18
> First of all thanks for your reply Currently, I set the retries to 20 and use quick node RPC.

I did not have good experience with Quick Node. Try a different RPC provider.

**Comment by umaid56** [comment] 2024-05-21 12:45
I guess Quick Node is the best of all. Do you recommend any other?

**Comment by AL-THE-BOT-FATHER** [comment] 2024-05-21 12:52
Alchemy or Helius.

**Comment by NotArchon** [comment] 2024-05-29 03:51
What are you guys setting the priority fee to?

**Comment by zerofill** [comment] 2024-06-02 18:09
Priority fee max is 5000000 lamports. .005 sol.
I just leave it at that or auto. When I set priority fees.

**Closed as completed** 2024-09-15 16:36 UTC
